### ISSUE TITLE
Error with VueRoute when jump to other route/page

### ISSUE THREAD

**Issue by iparker** [Labs64/GuideChimp#105]
Hello,

I trie to use GuideChimp inside a vue-nuxt-application.

I created a plugin for this and integrate this plugin in nuxt.config:

```
// plugins/vue-guidechimp.js
import Vue from 'vue';
import GuideChimp from 'guidechimp';
import 'guidechimp/dist/guidechimp.min.css';
import vueRouterPlugin from 'guidechimp/dist/plugins/vueRouter';

export default ({app}) => {
  GuideChimp.extend(vueRouterPlugin, app.router);

  Vue.use({
    install(V) {
      V.prototype.$guideChimp = GuideChimp;
    },
  });
};
```

This is working: I can trigger a demo tour and the steps  are displayed correctly.

But when I reach the step where I want to jump to anotuer page/route (I do this with route: this.localePath({name: 'myData'})) I get the following error (on the next page - so it seems loading the route works fine):

```
vueRouter.js?dd68:137 Uncaught (in promise) TypeError: Cannot read property 'catch' of undefined
    at _callee$ (vueRouter.js?dd68:137)
    at tryCatch (vueRouter.js?dd68:221)
    at Generator.invoke [as _invoke] (vueRouter.js?dd68:450)
    at Generator.prototype.<computed> [as next] (vueRouter.js?dd68:273)
    at asyncGeneratorStep (vueRouter.js?dd68:914)
    at _next (vueRouter.js?dd68:936)
    at eval (vueRouter.js?dd68:943)
    at new Promise (<anonymous>)
    at GuideChimp.eval (vueRouter.js?dd68:932)
    at GuideChimp.eval (vueRouter.js?dd68:148)
_callee$ @ vueRouter.js?dd68:137
tryCatch @ vueRouter.js?dd68:221
invoke @ vueRouter.js?dd68:450
prototype.<computed> @ vueRouter.js?dd68:273
asyncGeneratorStep @ vueRouter.js?dd68:914
_next @ vueRouter.js?dd68:936
eval @ vueRouter.js?dd68:943
eval @ vueRouter.js?dd68:932
eval @ vueRouter.js?dd68:148
eval @ guidechimp.js?b95d:2364
```

Hope you can help me with this.

Best regards,

Timo

**Comment by v-rudkovskiy** [comment]
Hello @iparker , can you tell me which version of GuideChimp you are using?

**Comment by iparker** [comment]
Thanks for your reply. I use GuideChimp in Version v3.3.0 and VueRouter-Plugin also in v3.3.0.

Or do you mean which version of vue router I use?

**Comment by v-rudkovskiy** [comment]
Hello @iparker , unfortunately  but I cannot repeat the problem. The only point where this error can occur is at the line... 
```javascript
  await router.push(route).catch(() => {});
```
Could you please check what router.push (route) returns.

**Comment by iparker** [comment]
Thanks for your reply. The router.push(route) returns an undefined. I also logged router.push in another component and this also returned undefined.

I tried to return just "return router.push(route);" without the catch-part in vueRouter.js. In this case I don't get the mentioned error but the selected element on the new page is wrong. Hard to explain the behaviour - there is a second selected element area and/or the selected element area is wrong. 

By the way: I had to reinstall guidechimp so I'm now in version 4.0.0.

**Comment by v-rudkovskiy** [comment]
@iparker Could you please check if your application supports Promise? If you look at the vue-router [code](https://github.com/vuejs/vue-router/blob/dev/src/index.js#L167), you can see that it returns a promise if only the environment supports it. For GuideChimp to work properly, you need your app to support Promises.

**Comment by iparker** [comment]
Thanks for your reply. Yes, our app uses promises everywhere. Think nuxt doesn't work without promises...

I just found this: https://github.com/nuxt/nuxt.js/issues/6951#issuecomment-729266427

Seems that nuxt doesn't use promises. So guidechimp will not work with nuxt? Or do you see another way?

**Comment by v-rudkovskiy** [comment]
@iparker I added the [pull request](https://github.com/Labs64/GuideChimp/pull/110) that fixed the problem with the nuxt framework. Soon it will be in the next version of GuideChimp.

**Comment by iparker** [comment]
Great - I'm happy to check the next version!

**Comment by iparker** [comment]
I just updated to new version 4.0.2 and it's working now. 

Unfortunately I have another error/problem with the selected/highlighted element but I will create a new issue for this.
