### ISSUE TITLE
Conflict with SweetAlert2

### ISSUE THREAD

**Issue by joshberg** [Labs64/GuideChimp#109]
**Describe the bug**
GuideChimp will not draw the modal overtop the SweetAlert2 modal; however, the element on the SweetAlert2 modal is highlighted properly.

**Screenshots**
![guidechimp_swal2-1](https://user-images.githubusercontent.com/7742454/119396888-14367c80-bc9b-11eb-8a37-18e7ea627c2d.png)
![guidechimp_swal2-2](https://user-images.githubusercontent.com/7742454/119396882-139de600-bc9b-11eb-973b-9ea5d1c0dcdf.png)

**To Reproduce**
1. Try to attach a GuideChimp tour event to a SweetAlert2 element.
2. Run the tour.

**Expected behavior**
GuideChimp should be able to draw on top of SweetAlert2 to continue the tour.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [90.0.4430.212]

**Additional context**
I am using the Lazy-loading plugin and the triggers plugin.

Rearranging the DOM elements and clicking around a bit allowed me to demonstrate the results I expected.
![guidechimp_swal2-3](https://user-images.githubusercontent.com/7742454/119399185-34b40600-bc9e-11eb-81e2-bd7d382683ea.png)
Before:
![guidechimp_swal2-4](https://user-images.githubusercontent.com/7742454/119399485-93797f80-bc9e-11eb-8d53-2230705ccdd3.png)
After:
![guidechimp_swal2-5](https://user-images.githubusercontent.com/7742454/119399390-747aed80-bc9e-11eb-9cc3-08beb18c7e39.png)

**Comment by v-rudkovskiy** [comment]
Hello @joshberg , can you tell me which version of GuideChimp and sweetAlert2 you are using?

No issues were found on Guidechimp v. 4.0 and sweetAlert2 v. 11. 

Here is my code: 

```javascript
   const tour = [{
        element: '#example',
        title: 'Title',
        description: 'Lorem ipsum...'
    }];

    const guide = GuideChimp(tour, { position: 'right' });

    Swal.fire({
        title: 'It is example!',
        html: '<span id="example" style="color: red">This element needs to be highlighted</span>',
        icon: 'info',
        confirmButtonText: 'Cool',
        didOpen() {
            guide.start();
        },
    })
```
And this result I have:

![Screenshot_3](https://user-images.githubusercontent.com/3775910/119979477-b324e680-bfc3-11eb-8484-933996c4b9ea.png)

**Comment by joshberg** [comment]
I am using GuideChimp 4.0 and SweetAlert2 6.4.2. Unfortunately there are a lot of breaking changes that keep us from updating to the latest version of SweetAlert2.

Here is my snippet that is responsible. The tour starts before the SweetAlert2 is displayed which is why I am using the lazy load plugin.

``` javascript
var tour = [];
      
tour.push({
    element: '#category-fav',
    title: 'Step 1: Deleting a Favorite',
    description: 'Open the Favorites category.',
    triggers: {
        next: {
            element: '#category-fav'
        }
    }
});
tour.push({
    element: '#dft-issues',
    title: 'Step 2: Deleting a Favorite',
    description: 'Click and hold on the defect you would like to remove from favorites.',
    triggers: {
        next: {
            element: '#dft-issues'
        }
    }
});
tour.push({
    element: '#modalContentId',
    title: 'Step 3: Deleting a Favorite',
    description: 'Click on the box or the words "Add (defect) to favorites" to uncheck the box.',
    triggers: {
        next: {
            element: '#addDefectToFavorites'
        }
    }
});
tour.push({
    element: 'swal2-confirm',
    title: 'Step 4: Deleting a Favorite',
    description: 'Click on Save Changes to save. Discard changes to cancel.',
    triggers: {
        next: {
            element: '.swal2-confirm'
        }
    }
});

GuideChimp(tour).start();
```

**Comment by v-rudkovskiy** [comment]
@joshberg  Hello, we are not able to reproduce this issue with older version of sweetAlert v6 as the documentation fo this version isn’t available public.
Any chance you could share documentation of test environment to investigate this issue?

**Comment by joshberg** [comment]
I can give the sweetalert2 files that we have in the project. I cannot release the other parts. Basically, I have list of divs contained in a div. When the user clicks on a specific div called out in the tour, it opens up a list of more divs (i.e. their favorites). The user performs an action on their favorites (long click) and a swal opens. The tour steps should display on their but they do not.
[sweetalert2.zip](https://github.com/Labs64/GuideChimp/files/6609034/sweetalert2.zip)

**Comment by v-rudkovskiy** [comment]
@joshberg I didn't find the css file in your zip archive. Is this a public website? Could you provide us the link here or via email at guidechimp@labs64.de

**Comment by joshberg** [comment]
Sorry about that. I do have a work around that is working for me. I modified the css line on GuideChimp from fixed to absolute:
```css
.gc .gc-fixed{
    position: absolute;
}
```
Granted it is not the best solution because I don't know what else will break, it is at least a workable solution so that I can move forward. Here is the CSS for that version of sweetalert2. Thank you for your help.
[sweetalert2.zip](https://github.com/Labs64/GuideChimp/files/6624020/sweetalert2.zip)

**Comment by v-rudkovskiy** [comment]
@joshberg I do not recommend that you change the styles of this class, otherwise the tour display may contain errors in some cases, I think you should pay attention to the sweetalert animation and start the tour after any animations. 

I haven't got any issues with sweetalert v6 with the js and css you gave me:

```javascript
// it is my code

const tour = [{
        element: '#example',
        title: 'Title',
        description: 'Lorem ipsum...'
    }];

const guide = GuideChimp(tour, { position: 'bottom' });

 swal({
        title: 'It is example!',
        html: '<span id="example" style="color: red">This element needs to be highlighted</span>',
        icon: 'info',
        confirmButtonText: 'Cool',
        onOpen() {
            setTimeout(() => {
                guide.start();
            }, 300);
        }
    });
```

![Screenshot_2](https://user-images.githubusercontent.com/3775910/121513535-9f31a980-c9f3-11eb-8fb2-60c43a5fac52.png)

**Comment by joshberg** [comment]
Unfortunately the sweet alert opens after the tour is going. It is part of the sequence... Is there a way to force the tour step to redraw? I could perhaps call the step to redraw after the alert is opened.

**Comment by v-rudkovskiy** [comment]
You can use the onBeforeChange event listener to delay the step: 

```javascript
const tour = [
        {
            element: '#example',
            title: 'Title',
            description: 'Lorem ipsum...',
            onBeforeChange() {
                return new Promise((s) => {
                    // delay of 500 ms
                    setTimeout(() => {
                        s();
                    }, 500);
                });
            }
        },
    ];
```

or if you whant to redraw use "refresh" function:

```javascript

    swal({
        title: 'It is example!',
        html: '<span id="example" style="color: red">This element needs to be highlighted</span>',
        icon: 'info',
        confirmButtonText: 'Cool',
        onOpen() {
          // refresh highlighting and position
           guide.refresh();
        }
    });
```

**Comment by joshberg** [comment]
I attempted both of those... They did not work for me. I ended up doing this.
```javascript
let guide = GuideChimp(tour);
let removedFixedInterval;
guide.on('onStart', function(){
    removedFixedInterval = setInterval(function(){
        $('.gc-control').removeClass('gc-fixed');
    }, 500);
});
guide.on('onStop|onComplete', function(){
    clearInterval(removedFixedInterval);
});
guide.start();
```

Still not the best, but visually it looks good and it does not modify the libraries at all. I'll consider this issue closed as we exhausted all avenues and I am content with my solution.
