### ISSUE TITLE
Problem with selected/highlighted element

### ISSUE THREAD

**Issue by iparker** [Labs64/GuideChimp#112]
Hello,

after solving my problem with vueRouter in a nuxt application with issue https://github.com/Labs64/GuideChimp/issues/105 I now have a problem with the selected/highlighted element.

Unfortunately it's hard to describe this behaviour. 

In some cases is not the right element is select. Seems like the whole height of the browser/window is selected instead. Or that that selected/hightlighted element is sticky or something - I don't get it.

Sometimes it also seems like there is a second highlighted element, and this element scrolls down when I scroll down the page.

When I look in DOM I see a structure like this:

svg.svg_overlay --> path-element --> animate-element.

When I try to delete the animate-element in DOM it seems better. In this way the hightlight-element-duplication is gone - for the current and the next steps.

Any ideas how to solve this?

Thanks for some help!

Best regards,

Timo

**Comment by v-rudkovskiy** [comment]
@iparker To help you please provide  the structure of html, css and the definition of the tour.

**Comment by iparker** [comment]
Thanks for your reply.

My test tour definition is:

```
const tour = [
        {
          element: '#step1',
          title: 'Step 1',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
          element: '.pb-form-navigation',
          title: 'Step 2',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          interaction: false,
        },
        {
          element: '.pb-dashboard-jobs',
          title: 'Step 3',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
          element: '#personal-data',
          title: 'Step 4 / Jetzt auf anderer Seite',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          route: this.localePath({name: 'myData'}),
        },
        {
          element: '#communication-data',
          title: 'Step 5 / Element im Formular nach Seitenwechsel',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
          element: '.pb-form-navigation',
          title: 'Step 6 / Navigation auch nach Seitenwechsel',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
        {
          element: '.pb-dashboard-jobs',
          title: 'Step 7 / zurück zum Dashboard',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          route: this.localePath({name: 'myDashboard'}),
        },
        {
          element: '.pb-form-navigation',
          title: 'Step 8',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        },
      ];

      const guide = this.$guideChimp(tour);

      document.getElementById('startTour').onclick = () => {
        guide.start();
      };
```

This code comes from mouted() of a vue component.

I don't know how to provide html/css structure to you. I'm not able to do this.

**Comment by v-rudkovskiy** [comment]
@iparker The tour definition looks fine. 

If you not abble provide html/css, could you provide:
- screenshot of issue
- data to the getBoundingClientRect() function for the highlighted element and copy the html structure of the .svg-overlay element.

**Comment by iparker** [comment]
Again thanks for your reply. Hope this input will help you.

![guidechimp_screen](https://user-images.githubusercontent.com/2860486/120311598-f939bd00-c2d7-11eb-9409-5e6001c7a245.png)

```
<svg class="svg-overlay"> <path d="M 0 0 H 1301 V 6335 H 0 V 0 ZM 465.15557861328125 751.9222412109375
                 a 4,4 0 0 0 -4,4
                 V 1377.0333862304688
                 a 4,4 0 0 0 4,4
                 H 1231.1444702148438
                 a 4,4 0 0 0 4,-4
                 V 755.9222412109375
                 a 4,4 0 0 0 -4,-4Z"> <animate attributeName="d" fill="freeze" dur="200ms"></animate> </path> </svg>
```

Sorry I don't know how to give you the data to the getBoundingClientRect() function for the highlighted element. Maybe you can tell me to get this?

**Comment by r-brown** [comment]
@iparker is this a public website? So you could simply provide us the link here or via email at guidechimp@labs64.de

**Comment by iparker** [comment]
No sorry - the website is not public but only on my localhost.

**Comment by v-rudkovskiy** [comment]
@iparker 
To get data from getBoundingClientRect () you need to execute the code(GuideChimp must be started): 
```javascript
document.querySelector('.gc-highlight').getBoundingClientRect();
``` 
Based on the svg path, I don't see it drawing two squares, run the below code(GuideChimp must be started), it should be 1
```javascript
document.querySelectorAll('.gc-overlay').length
```

**Comment by iparker** [comment]
Thanks for your reply. Here is the feedback.

document.querySelector('.gc-highlight').getBoundingClientRect():

DOMRect {x: 465.15557861328125, y: 692.6333618164062, width: 765.9888916015625, height: 621.1111450195312, top: 692.6333618164062, …}
bottom: 1313.7445068359375
height: 621.1111450195312
left: 465.15557861328125
right: 1231.1444702148438
top: 692.6333618164062
width: 765.9888916015625
x: 465.15557861328125
y: 692.6333618164062
__proto__: DOMRect

document.querySelectorAll('.gc-overlay').length:
1

My browser: Version 90.0.4430.93 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)

I don't know why I see two squares...

**Comment by v-rudkovskiy** [comment]
@iparker Have you tried opening in a different browser and do you have the ability to place this page in the public domain, for example, in the codepen?

**Comment by iparker** [comment]
You are right - I don't have this double-square-error in firefox. Damn...

Unfortunately I can't place the page on a public domain.

**Comment by v-rudkovskiy** [comment]
I suspect this may be a browser bug...

**Comment by iparker** [comment]
Hello,

I just installed Chrome (Version 91.0.4472.77 (Offizieller Build) (64-Bit)) but I have the same issue in this browser version.

Best regards,

Timo

**Comment by v-rudkovskiy** [comment]
@iparker  You were right in chrome there were problems with the animate when scrolling and moving from a step with an element to a step without an element.

PR that fix it: https://github.com/Labs64/GuideChimp/pull/115

This fix will be in a new version soon. Please write if this fix helped you.

**Comment by r-brown** [comment]
Fix added to the release [4.0.3](https://github.com/Labs64/GuideChimp/releases/tag/4.0.3)

**Comment by iparker** [comment]
Thanks for your fix and the update. With update to version 4.0.3 the problem with the duplication is solved.

It just seems that sometimes the selected area is too small and cropped on the right side.

**Comment by v-rudkovskiy** [comment]
@iparker This might be the case if your application has an animation to display the selected item. Because the GuideChimp higlights and positions itself based on the size and position of the element, during animation, the higlighted element may have a different size and position from its original(resting) state. You can use the "onBeforeChange" event listener to wait for the animation to complete. 

Take as an example animation using animate.css:
```javascript
guide.on('onBeforeChange', async (to) => {
        const el = this.getStepEl(to);

        await new Promise((s) => {
            const isAnimationInProcess = () => {
                return el.classList.contains('animate__animated');
            };

            if (!isAnimationInProcess()) {
                s();
            } else {
                const interval = setInterval(() => {
                    if (!isAnimationInProcess()) {
                        s();
                        clearInterval(interval);
                    }
                }, 100);
            }
        });
    });
```
