### ISSUE TITLE
Licensing works on localhost with HTTP/HTTPS but will not work on server using HTTP

### ISSUE THREAD

**Issue by joshberg** [Labs64/GuideChimp#116]
**Describe the bug**
The licensing plugin does not seem to function properly using HTTP on my production server. It just hangs.

**To Reproduce**
1. Try to access guidechimp on a server through HTTP instead of HTTPS

**Expected behavior**
I expected it to function the same in my production environment as it did in my dev environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/7742454/121939732-ee891a00-cd12-11eb-961e-fc0ef9423a49.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2021 R2
 - Browser: Chrome
 - Version: 91.0.4472.101 (Official Build) (64-bit) (cohort: 91_Win_77)

**Additional context**
There is nothing in the plugin documentation that states it requires HTTPS.

**Comment by v-rudkovskiy** [comment]
Hello @joshberg 

In the licensing module we use [WebCrypto API](https://www.chromium.org/blink/webcrypto), access to the [WebCrypto API](https://www.chromium.org/blink/webcrypto) is restricted to "[secure origins](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features)" and crypto.subtle is supposed to be undefined in insecure contexts.

“[Secure origins](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features)” are origins that match at least one of the following (scheme, host, port) patterns: 
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —) 

Why are you using unsecured http for your production environment?

**Comment by joshberg** [comment]
It is an internal only web application. There is no access from the outside internet. I am in the process of converting it to https because of incompatibilities like these. Thank you for explanation.
