### ISSUE TITLE
Labs64 contact us form

### ISSUE THREAD

**Issue by joshberg** [Labs64/GuideChimp#118]
I apologize for reaching out on here but I have not been able to get a hold of anyone through the contact form or through info@labs64.com.

**Describe the bug**
It appears the contact form on the labs64 page for guidechimp does not appear to be working properly. 

**To Reproduce**
1. Submit a request through the contact form.
2. Wait for 2 weeks for a response

**Expected behavior**
An automated email confirmation of the submission form.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 91.0.4472.106

**Comment by r-brown** [comment]
Hi @joshberg thank you for this notice - we'll fix the contact form.
In urgent case you can also use following emails to reach out to us:

- info@labs64.com
- guidechimp@labs64.com

**Comment by r-brown** [comment]
Contact form functionality restored, all notifications will be addressed.
