### ISSUE TITLE
Enlarge the highlighted zone

### ISSUE THREAD

**Issue by John-Gee** [Labs64/GuideChimp#120]
Apologies if that's already feasible, I could not figure it out by looking at the CSS file.

**Describe the solution you'd like**
Allow the highlighted zone to be bigger than the associated element.
Being able to specify a percentage would be enough for me, but maybe a setting for all 4 sides like with padding would make more sense? Maybe allowing to both grow and shrink would too?

Thank you!

**Comment by v-rudkovskiy** [comment]
@John-Gee you can use the "[padding](https://github.com/Labs64/GuideChimp/wiki/Configure#options)" option, which you can set as global for each step of the tour, or in the step definition

**Comment by John-Gee** [comment]
Yup, my apologies, your doc that I read, or more likely thought I did read correctly, is pretty clear about that.

(and yes it works!)

Thank you and sorry again!
