### ISSUE TITLE
Guidechimp attribution issue.

### ISSUE THREAD

**Issue by tyagirajat200** [Labs64/GuideChimp#122]
When I start the tour there is a attribution "Made with Guidechimp". I already have a license that says we can use it on 3 domains, I integrated the guidechimp with 2 domains and each domain has local , development , production environment I think this might be the case when I exceed the domains limit. Can you please help to avoid this attribution issue. Hoping for quick reply as this issue is very urgent to fix.

**Comment by r-brown** [comment]
Hello @tyagirajat200 
attribution isn't necessary related to the domain count - you only need to configure [Remove Attribution plugin](https://github.com/Labs64/GuideChimp/wiki/Remove-Attribution-plugin)

In regards to the domain count - we are not able to distinguish logical environments on your side (e.g. dev, prod, etc.).
The only relevant info for us is domain name and this is being counted.

If you feel your setup is not correct, we advise you to share your license number with us via guidechimp@labs64.com or contact form on the website.

**Comment by tyagirajat200** [comment]
Mailed you the details. Please check.

**Comment by r-brown** [comment]
> Mailed you the details. Please check.

still no email received - may I ask you to resend via our [contact](https://www.labs64.com/contact/) form please

**Comment by tyagirajat200** [comment]
done

**Comment by tyagirajat200** [comment]
> > Mailed you the details. Please check.
> 
> still no email received - may I ask you to resend via our [contact](https://www.labs64.com/contact/) form please

Resend the details via contact form. We are looking forward to your earliest response.

**Comment by tyagirajat200** [comment]
Any update on this ??
