### ISSUE TITLE
How can I get the context that I send on moving next step

### ISSUE THREAD

**Issue by anonymous9915** [Labs64/GuideChimp#123]
Question
How can I get the context that I send on moving next step like-: Guidechimp.next({programmatically : true}). I want to catch this on my before change event listener but I am not getting this. I know that I can use it on next event listener but my use case is different I have to catch it in beforeChange listener. Is it possible ??

**Comment by r-brown** [comment]
**Question**
How can I get the context that I send on moving next step like-: Guidechimp.next({programmatically : true}). I want to catch this on my before change event listener but I am not getting this. I know that I can use it on next event listener but my use case is different I have to catch it in beforeChange listener. Is it possible ??

**Comment by v-rudkovskiy** [comment]
Hello @anonymous9915 

```javascript
    const guide = GuideChimp(tour);

    guide.on('onBeforeChange', (toStep, fromStep, context) => {
        console.log(context); // { programmatically : true }
    });

    guide.next({ programmatically : true });
```
