### ISSUE TITLE
Interaction with highlighted element is not working in angular 7

### ISSUE THREAD

**Issue by nagagopi040** [Labs64/GuideChimp#124]
We are using GuideChimp in angular 7. On Top of this, we are using the angular-material-fuse theme. The highlighted element is not clickable even though we configured interaction as `true`.

**Comment by r-brown** [comment]
Hello @nagagopi040 please provide additional context to this issue:
- GuideChimp version and Plugins used
- sample (public) webpage with GuideChimp integrated
- GuideChimp configuration details (module and steps definition)

**Comment by nagagopi040** [comment]
- GuideChimp version: 4.0.4

- We don't have public webpage.

- Configuration:

   const options = {
      interaction: true,
      exitEscape: false,
      exitOverlay: false,
      scrollBehavior: 'smooth',
      showPagination: false,
      useKeyboard: false
    };
    GuideChimp(steps, options);

- Steps:

const steps = [{
        element: '#step-1',
        description: 'This is step 1',
        title: 'Step 1',
        interaction: true
    }, {
        element: '#step-2',
        description: 'This is step 1',
        title: 'Step 2',
        interaction: true
    }]

- Plugins:
1. licensing
2. placeholders
3. removeAttribution

**Comment by r-brown** [comment]
Thank you @nagagopi040 - any chance to share webpage via email ( gudechimp@labs64.com ) or give our dev team temporary access to your environment?
As you can understand, we won't be able to troubleshot the issue without being able to see the system behavoiur.

**Comment by nagagopi040** [comment]
Here is our public link: [http://codejudge-web-dev.s3-website-us-east-1.amazonaws.com/contests/contest-demo/2366]

**Comment by v-rudkovskiy** [comment]
Hi @nagagopi040 There was a problem with the z-index stacking-context. 

PR that fix it: #126 

This fix will be in a new version soon.

**Comment by r-brown** [comment]
Hello @nagagopi040 - thank you for reporting this issue!
We fixed this in the latest GuideChimp release [4.0.5](https://github.com/Labs64/GuideChimp/releases/tag/4.0.5)

Would you mind to update this version on your side and test fix?

**Comment by nagagopi040** [comment]
it's working in version: 4.0.5
