### ISSUE TITLE
Highlighting of the target element fails

### ISSUE THREAD

**Issue by kkorotkov** [Labs64/GuideChimp#15]
**Describe the bug**
In case an element to be highlighted is inside container having own `z-index` + `transform` styles, highlighting fails (target stays under the highlighting box).

**To Reproduce**
HTML:
```
<script src="https://cdn.jsdelivr.net/npm/guidechimp/dist/guidechimp.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/guidechimp/dist/guidechimp.min.css">
<div id="myel1">myel1</div>
<div style="z-index:100;transform:translateX(10px)">  
  <div id="myel2">myel2</div>
</div>
<div>
  <button id="startTour" class="start-tour">Start Tour</button>
</div>
```

JS:
```
var tour = [
    {
        element: '#myel1',
        title: 'Regular element',
        description: 'Highliting works as expected'
    },
    {
        element: '#myel2',
        title: 'Element having own z-index + transform',
        description: 'Target is not properly highlited'
    }
];
var guideChimp = new GuideChimp(tour);
document.getElementById('startTour').onclick = function () {
    guideChimp.start();
};
```

**Expected behavior**
Element at step 2 must be visible

**Comment by kkorotkov** [comment]
Highlighting works as expected:
<img width="180" alt="good" src="https://user-images.githubusercontent.com/1833750/74594722-d9767b00-5039-11ea-883c-e21e82863580.png">

Highlighting fails:
<img width="190" alt="bad" src="https://user-images.githubusercontent.com/1833750/74594737-f14dff00-5039-11ea-9c02-b01b4cd30bef.png">

**Comment by r-brown** [comment]
implemented
