### ISSUE TITLE
HTML step configuration data-guidechimp-interaction boolean value does not work

### ISSUE THREAD

**Issue by dmytro-shchurov** [Labs64/GuideChimp#150]
According to a standard, HTML boolean values:

```
A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

If the attribute is present, its value must either be the empty string or a value that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the attribute's canonical name, with no leading or trailing whitespace.
```

Your `typeof this.currentStep.interaction === 'boolean'` does not work. I tried both: global disable + attribute enable, and global enable + attribute disable, different attribute values (empty string and attribute without a value including) with no success.

Only a global `options.interaction` works.

Browser Chrome 104.
OS Win 10

**Comment by v-rudkovskiy** [comment]
Hello @dmytro-shchurov, testing have not shown any issues with interaction. Could you give example of your implementation?

**Comment by v-rudkovskiy** [comment]
@dmytro-shchurov Could you mean while solve your issue?
