### ISSUE TITLE
Placeholders in JS tour definition

### ISSUE THREAD

**Issue by kkorotkov** [Labs64/GuideChimp#16]
In a single-page web application, DOM most likely contains elements with dynamically generated Id (or other properties that are to be used for element selection). In such dynamic environment, static tours definition is not possible. Possible solution is to embed tours within application, so the tours are generated together with the rest of DOM, but this often may not be desirable due to number of concerns.

Alternative, is to allow certain dynamic parts in static JS tour definition in a form of expandable variables, that are expanded at the tour start.

Example:
```
var tour = [
    {
        element: '#element-${dynamic_id}',
        title: 'Step 1',
        description: 'Click ${dynamic_text} to modify its properties.'
    }
];
var guideChimp = new GuideChimp(tour);
guideChimp.start({dynamic_id: '7fa1', dynamic_text: 'MyEditableItem'});

```

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/56

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/57

**Comment by r-brown** [comment]
[Placeholders](https://github.com/Labs64/GuideChimp/tree/master/plugins/placeholders) plugin - Use dynamic placeholders in the tour definition.
