### ISSUE TITLE
Add plugin boilerplate

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#21]

**Comment by v-rudkovskiy** [comment]
Commin c698847

**Comment by r-brown** [comment]
@v-rudkovskiy IMO this is too much (separate build flow) - need to be discussed.

**Comment by r-brown** [comment]
@v-rudkovskiy please always use source code license disclaimer; see example here https://github.com/Labs64/GuideChimp/blob/master/src/index.js#L7
