### ISSUE TITLE
React.js showcase

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#32]
Showcase GuideChimp usage in the React applications.

- Use React dashboard template here https://codesandbox.io/search?query=dashboad&refinementList[template][0]=create-react-app
- Fork selected sandbox
- Add GuideChimp

**Comment by r-brown** [comment]
Good templates:
- https://codesandbox.io/s/dashboard-420cz

**Comment by giubatt** [comment]
I made a codesandbox but I'm not sure where to add it to open a PR

**Comment by r-brown** [comment]
That's great @giubatt 
Please add this to https://github.com/Labs64/GuideChimp#demo
We'll verify this demo and extend Wiki at https://github.com/Labs64/GuideChimp/wiki/Examples (as you might not have the permissions to edit this)

**Comment by r-brown** [comment]
That's awesome @giubatt - thank you!!

Slightly modified readme - https://github.com/Labs64/GuideChimp#demo
... as well wiki - https://github.com/Labs64/GuideChimp/wiki/Examples

---

https://github.com/Labs64/GuideChimp/stargazers ;)
