### ISSUE TITLE
Button with img not responding in Guidechimp

### ISSUE THREAD

**Issue by Coeniq** [Labs64/GuideChimp#40]
**Button that contains an image doesn't register onclick in Guidechimp**
I am currently trying to setup Guidechimp and wanted to set a trigger to click on a Button, similar to the examples on codepen. The main difference is, that the button encapsules an image and when I click the image it doesn't register the click.
When I click on the fine border between image and buttonborder it registers, but that isn't explainable to the end users.

**To Reproduce**
1. have a `<button type="button"><img src...></button>`
2. have a guidechimp trigger set to 
```
triggers:{
            next:{
                element: ...[theButton]...
                event: 'click',
                listener(e){
                  
                    this.next(); 

                }
            },
```
3. Click on the image inside the button
4. See no nextstep

**Expected behavior**
the image should register just as the button itself does

 - Browser: Chrome
 - Version 1.7.7

**Comment by v-rudkovskiy** [comment]
Thanks @Coeniq , the bug has been fixed, the fix will be added to the new guidechimp version

**Comment by r-brown** [comment]
Add test case

**Comment by r-brown** [comment]
Test case / proof needed

**Comment by v-rudkovskiy** [comment]
Test case: https://codepen.io/v-rudkovskiy/pen/oNLvqBp

**Comment by Coeniq** [comment]
Thanks @v-rudkovskiy looking forward to using it.
