### ISSUE TITLE
Element Highlighted yet unable to interact with the element

### ISSUE THREAD

**Issue by saravananselvamohan** [Labs64/GuideChimp#42]
**Describe the bug**
We testing a Guidechimp in a custom site. With the site we able to have element highlighted as per tour steps yet unable to interact with the element.
I checked we didn't disabled interaction layer from the tour options. May I know the checks I am missing. I tested with other sites and Guidechimp flow working perfect. The issue is with my custom site

**Expected behavior**
Able to  interact with the element in DOM

**Screenshots**

![issue](https://user-images.githubusercontent.com/43172875/95426465-8d2ed100-0963-11eb-9a23-8617e1044730.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Chrome
 - Version 85

**Comment by r-brown** [comment]
Hi @saravananselvamohan would you mind to provide us with the website DOM and GuideChimp tour definition, so we can reproduce this behaviour.

Possibly CodePen would be used here to provide HTML, CSS, JS code

**Comment by saravananselvamohan** [comment]
Hi @r-brown . The issue is with Salesforce developer site

**Comment by r-brown** [comment]
That's would be OK (as we do have access to SF dev/prod).
In this case, may I ask you to provide more context:
- which SF component you are trying to interact with
- your tour definition

If privacy is a concern here - you can send this data directly to guidechimp@labs64.com

**Comment by r-brown** [comment]
In regards to loading external tours on the websites with the same-origin policy enabled (e.g. Salesforce) - we need to investigate on the permissions available in the extension.

**Comment by saravananselvamohan** [comment]
@r-brown . Is there any sample documentation for onBeforeChange(), onAfterChange() as how to be used in Javascript object. It would help newcomers. If you guide me I would like to add that in documentation too,please

**Comment by r-brown** [comment]
Hello @saravananselvamohan 
- docu extended - https://github.com/Labs64/GuideChimp/wiki/Configure#events
- new sample added (JS events / `onBeforeChange`) - https://github.com/Labs64/GuideChimp/wiki/Examples (playground: https://codepen.io/netlicensing/full/BazaXYo)

**Comment by saravananselvamohan** [comment]
@r-brown . Thanks for the ton of help. Is there any way we can prevent tour from moving to previous steps from a particular step.

**Comment by r-brown** [comment]
@saravananselvamohan you can use the same `onBeforeChange` event here:
```
guideChimp.on('onBeforeChange', (to, from)=>{
  if ( to < from ) {
    return false;
  }
});
```

**Comment by saravananselvamohan** [comment]
> **Describe the bug**
> We testing a Guidechimp in a custom site. With the site we able to have element highlighted as per tour steps yet unable to interact with the element.
> I checked we didn't disabled interaction layer from the tour options. May I know the checks I am missing. I tested with other sites and Guidechimp flow working perfect. The issue is with my custom site
> 
> **Expected behavior**
> Able to interact with the element in DOM
> 
> **Screenshots**
> 
> ![issue](https://user-images.githubusercontent.com/43172875/95426465-8d2ed100-0963-11eb-9a23-8617e1044730.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 20
> * Browser Chrome
> * Version 85

@r-brown . The issue is closely related to z-index value.

**Comment by r-brown** [comment]
@saravananselvamohan we tested this issue on our side and changing z-index didn't have any effect. Very complex DOM / CSS structure at SalesForce forces this.

Did you manage to fix this behaviour by changing z-index?

**Comment by saravananselvamohan** [comment]
> @saravananselvamohan we tested this issue on our side and changing z-index didn't have any effect. Very complex DOM / CSS structure at SalesForce forces this.
> 
> Did you manage to fix this behaviour by changing z-index?

We able to remove the z -index does removes overlay too. So we can interact with element. But Ideally we need to have highlighter that's still an issue

**Comment by saravananselvamohan** [comment]
> @saravananselvamohan we tested this issue on our side and changing z-index didn't have any effect. Very complex DOM / CSS structure at SalesForce forces this.
> 
> Did you manage to fix this behaviour by changing z-index?

Is there any way, we can able to highlight the element removing overlay and interaction layer

**Comment by r-brown** [comment]
@saravananselvamohan you can always add/override your own CSS styles to fix specific layouts (such as SF) - https://github.com/Labs64/GuideChimp/wiki/Configure#styling

**Comment by saravananselvamohan** [comment]
> @saravananselvamohan you can always add/override your own CSS styles to fix specific layouts (such as SF) - https://github.com/Labs64/GuideChimp/wiki/Configure#styling

Will able to resolve those issue by custom css options. Thanks for the help @r-brown. Would like to close the issue

**Comment by r-brown** [comment]
Hello @saravananselvamohan ,

Coming back to the above discussion I wanted to inform you that we released and published first version of [GuideChimp Chrome Extension](https://chrome.google.com/webstore/detail/guidechimp-chrome-extensi/afecedbgkfoijeligfjflidfddndnjng).

With this extension you guided tour can be enabled on any website with no-coding effort.
The tours definitions for public websites and web apps can be published through the Pull Request at https://github.com/Labs64/GuideChimp/tree/master/docs/guidechimp/tours
