### ISSUE TITLE
IE11 bugs

### ISSUE THREAD

**Issue by yushkevich** [Labs64/GuideChimp#44]
**Describe the bug**
There are a few IE11 visualization issues. 
1. Modal window is not centered. 
2. Arrows are invisible. 

![2020-10-12_12-04-54](https://user-images.githubusercontent.com/3961540/95728019-a6958d00-0c83-11eb-8022-9c4f54a7c330.png)

**Desktop (please complete the following information):**
 - Browser IE11

**Comment by yushkevich** [comment]
Hello @r-brown 
Any updates here?

**Comment by r-brown** [comment]
- End support for Internet Explorer 11 scheduled on _August 17th, 2021_
- Browser usage stats is [less than 2%](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers)

=> ticket will be closed
