### ISSUE TITLE
Expandable menu wrong highlighting

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#51]
**Describe the bug**
In the case of the (left nav) expandable menu, the highlighting is correct if the main menu item collapsed.
In case the menu is expanded, the highlighted area positioned wrongly.

**To Reproduce**
Use any collapsible menu structure to reproduce.

**Expected behavior**
Element highlighting placed correctly.

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/52
