### ISSUE TITLE
Lazy-loading plugin

### ISSUE THREAD

**Issue by v-rudkovskiy** [Labs64/GuideChimp#53]

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/54

**Comment by r-brown** [comment]
[Lazy-loading](https://github.com/Labs64/GuideChimp/tree/master/plugins/lazyLoading) plugin - Wait for lazy-loaded or delayed elements on the page before showing related tour step.
