### ISSUE TITLE
Visibility of a highlighted element

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#55]
> Visibility of a highlighted element when the element (e.e. button) is without background colour with light coloured text is quite bad.
The content of the highlighted area is not readable enough then.

**Comment by ionstudio** [comment]
> > Visibility of a highlighted element when the element (e.e. button) is without background colour with light coloured text is quite bad.
> > The content of the highlighted area is not readable enough then.

Did you solve the problem?
