### ISSUE TITLE
IFrames support

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#59]
**Is your feature request related to a problem? Please describe.**
Add IFrames support in the GuideChimp

**Describe the solution you'd like**
Introduce a new plugin which will allow specify and highlight elements in the IFrame.
Pay attention to the tool-tip position if the element in the iframe will be highlighted.

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/61
