### ISSUE TITLE
IFrame plugin: Nested HTML table throws an error

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#66]
**Describe the bug**
IFrame plugin: Nested HTML table throws an error in most of the browsers; e.g. Chrome, Safari

**To Reproduce**
Test https://io.labs64.com/iframe0.html with the different browsers.

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/68
PR: https://github.com/Labs64/GuideChimp-plugins/pull/3
