### ISSUE TITLE
Triggers plugin doesn't work (v3.x)

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#72]
**Describe the bug**
https://codepen.io/netlicensing/pen/PoPawdv

**Comment by v-rudkovskiy** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/3775910/103527280-2736e480-4e93-11eb-9df0-b5c773d70e1e.png)

You need to add a closing tag </script>  on 2 line after "licensing.js"

**Comment by r-brown** [comment]
works :)
