### ISSUE TITLE
Improve insufficiend domains count message

### ISSUE THREAD

**Issue by r-brown** [Labs64/GuideChimp#91]
Given following scenario:
- [GiudeChimp commercial plugin](https://www.labs64.com/guidechimp/#guidechimp-licensing) is enabled in customer profile
- There are no free domains available
- ... or current domain (where GuideChimp is running) exceeding available domains count

following message appears:
`GuideChimp [IFRAMES-PLUGIN]: this plugin is not enabled for your customer profile; see also https://www.labs64.com/guidechimp/#guidechimp-licensing`

---

Expected:
`GuideChimp [LICENSING]: domains exceeded the available domains count; see also https://www.labs64.com/guidechimp/#guidechimp-licensing`

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp-plugins/pull/8
