### ISSUE TITLE
Guidechimp licensing  plugin not working

### ISSUE THREAD

**Issue by tyagirajat200** [Labs64/GuideChimp#95]
**Describe the bug**
Purchased Guidechimp license to remove Attribution and to use commercial plugins. but when I start the tour or changes any step I got the errors. please find attached screenshots.

**To Reproduce**
Import Modules
import licensing from 'guidechimp/dist/plugins/licensing';
import removeAttribution from 'guidechimp/dist/plugins/removeAttribution';
GuideChimp.extend(licensing, { id: 'XXXXXXXXX' });
GuideChimp.extend(removeAttribution);

**Desktop (please complete the following information):**
  - Device: Laptop
 - OS:  Windows 10 (64-bit)
 - Browser : Chrome
 - Version 90.0.4430.72 (Official Build) (64-bit)

**Additional context**
![Screenshot (104)](https://user-images.githubusercontent.com/40917672/115865167-9726a600-a455-11eb-83b0-a7c05290eca3.png)
![Screenshot (105)](https://user-images.githubusercontent.com/40917672/115865173-99890000-a455-11eb-9062-f0069133c5d4.png)

**Comment by r-brown** [comment]
Hello @tyagirajat200 apologies for that, the issue is related to the License Management provider and fixed now.
Would you mind to try it again?

**Comment by tyagirajat200** [comment]
working now. thank you
