### ISSUE TITLE
Is there a way to distinguish between tour closed by user or closed by programmatically when listening  'onStop' events.

### ISSUE THREAD

**Issue by tyagirajat200** [Labs64/GuideChimp#96]

**Comment by v-rudkovskiy** [comment]
The stop method is called only after user actions: closing the tour with a cross, clicking on the overlay, pressing the escape key, so all calls to the stop event are due to the user.

**Comment by tyagirajat200** [comment]
if i call guidechimp.stop() then also stop event triggers

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/98
Added the ability to pass context to the onStop, onPrevious and onNext events in the stop, previous and next methods. In addition, the event object that the user called to close the tour is now passed as the context. 

You can based on event property in context, example:
```javascript
const guide = GuideChimp(tour);

guide.on('onStop', (context) => {
    const { event } = context || {};

    if (event) {
        // the user has closed the tour 
    } else {
        // tour was closed programmatically
    }
});
```

Or add your property to the context:
```javascript
guide.stop({ stopProgrammatically: true });

guide.on('onStop', (context) => {
    const { stopProgrammatically } = context || {};

    if (stopProgrammatically) {
         // tour was closed programmatically
    } else {
      // the user has closed the tour 
    }
});
```

**Comment by tyagirajat200** [comment]
Awesome

**Comment by r-brown** [comment]
Just release v3.3.0 which is including this change: https://github.com/Labs64/GuideChimp/releases/tag/3.3.0

**Comment by r-brown** [comment]
Documentation updated: https://github.com/Labs64/GuideChimp/wiki/Configure#methods
