### ISSUE TITLE
Element highlight problem

### ISSUE THREAD

**Issue by ionstudio** [Labs64/GuideChimp#97]
Hey! Such a problem, there is a strange background in the left menu and nothing is visible. We tried to do something with CSS styles, but without results.

Normal.
![1](https://user-images.githubusercontent.com/20832474/116088377-0279ad80-a6cc-11eb-8af7-32ea77ea5a76.png)

Element highlighting problem.
![2](https://user-images.githubusercontent.com/20832474/116088381-03aada80-a6cc-11eb-9487-c5a156189d48.png)

Other elements are highlighted normally.
![3](https://user-images.githubusercontent.com/20832474/116088387-04437100-a6cc-11eb-94a9-2cd1802ddcc0.png)

**Comment by v-rudkovskiy** [comment]
Hello @ionstudio. Can you provide more information on the layout and styles of your left menu, or provide a link where I can see this myself?

**Comment by ionstudio** [comment]
> Hello @ionstudio. Can you provide more information on the layout and styles of your left menu, or provide a link where I can see this myself?

https://wbtest.pro/dashboard/
test@test.test
Jd83nd!d9

**Comment by tyagirajat200** [comment]
Hello @ionstudio  @v-rudkovskiy . I am aware about this issue. this happens when your element or it's parent element have any animation or transform property .

**Comment by ionstudio** [comment]
The same thing happens with the top menu that is fixed.

![Безымянный](https://user-images.githubusercontent.com/20832474/116228291-4c6f9b80-a77f-11eb-95a6-7ac85879ce04.png)

**Comment by r-brown** [comment]
Hello @ionstudio - thank you for reporting this element highlighting issue. Indeed, there might be some conflicting CSS background colours. We'll try to address this with the next GuideChimp release.

**Comment by tyagirajat200** [comment]
![Capture](https://user-images.githubusercontent.com/40917672/116259902-dc1f4500-a793-11eb-8ac2-581395fb1aa5.PNG)
Got the same issue today again to fix this I have to disable the animation.
